### ISSUE TITLE
Desperate to get this incredible tool installed on my computer...

### ISSUE THREAD

**Issue by JonasIsLive** [jungdj/AI-Effects#15]
Hey.. im a bit desperate here.. I've tried for multiple weeks to get this tool installed now.. ive tried with different versions of tensorflow and all sorts of other tweaks.. I keep running into some kind of issue with the tensorflow package.. If i try with the newest tensorflow (2.4) then i get this error: 
ModuleNotFoundError: No module named 'tensorflow.contrib'

If i use the 1.14 version then i get this error:
_pywrap_tensorflow_internal no module named

There is something super basic I'm doing wrong.. but i would really love to get this project up and running as it is absolutely incredible.. Can anyone please help ??

**Comment by JonasIsLive** [comment]
(base) jonasbjerg@jsb python_server % ./install.sh
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0
ERROR: No matching distribution found for tensorflow==1.14.0
Requirement already satisfied: cython in /usr/local/lib/python3.8/site-packages (0.29.21)
Collecting pycocotools==2.0
  Using cached pycocotools-2.0.0.tar.gz (1.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-install-08u9vv_7/pycocotools_f902b7962dd2429eb74e29a849c5adb2/setup.py'"'"'; __file__='"'"'/private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-install-08u9vv_7/pycocotools_f902b7962dd2429eb74e29a849c5adb2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-pip-egg-info-wqv_oai3
         cwd: /private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-install-08u9vv_7/pycocotools_f902b7962dd2429eb74e29a849c5adb2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-install-08u9vv_7/pycocotools_f902b7962dd2429eb74e29a849c5adb2/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(base) jonasbjerg@jsb python_server % python --version
Python 3.7.9
(base) jonasbjerg@jsb python_server % python -c "import sys; print(sys.version)"
3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ]
(base) jonasbjerg@jsb python_server % pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl
Collecting tensorflow==1.14.0
  Downloading https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl (105.8 MB)
     |████████████████████████████████| 105.8 MB 162 kB/s 
Requirement already satisfied: six>=1.10.0 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (1.15.0)
Requirement already satisfied: absl-py>=0.7.0 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (0.11.0)
Requirement already satisfied: keras-applications>=1.0.6 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (1.0.8)
Requirement already satisfied: termcolor>=1.1.0 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (1.1.0)
Requirement already satisfied: wrapt>=1.11.1 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (1.11.2)
Requirement already satisfied: protobuf>=3.6.1 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (3.13.0)
Requirement already satisfied: google-pasta>=0.1.6 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (0.2.0)
Requirement already satisfied: grpcio>=1.8.6 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (1.31.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (1.1.2)
Requirement already satisfied: gast>=0.2.0 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (0.4.0)
Requirement already satisfied: astor>=0.6.0 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (0.8.1)
Requirement already satisfied: numpy<2.0,>=1.14.5 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (1.19.2)
Requirement already satisfied: wheel>=0.26 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorflow==1.14.0) (0.36.2)
Requirement already satisfied: h5py in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from keras-applications>=1.0.6->tensorflow==1.14.0) (2.10.0)
Requirement already satisfied: setuptools in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from protobuf>=3.6.1->tensorflow==1.14.0) (51.0.0.post20201207)
Collecting tensorboard<1.15.0,>=1.14.0
  Downloading tensorboard-1.14.0-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 4.0 MB/s 
Requirement already satisfied: markdown>=2.6.8 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0) (3.3.3)
Requirement already satisfied: werkzeug>=0.11.15 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0) (1.0.1)
Requirement already satisfied: importlib-metadata in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0) (2.0.0)
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0
  Downloading tensorflow_estimator-1.14.0-py2.py3-none-any.whl (488 kB)
     |████████████████████████████████| 488 kB 1.2 MB/s 
Requirement already satisfied: zipp>=0.5 in /Users/jonasbjerg/opt/anaconda3/lib/python3.7/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0) (3.4.0)
Installing collected packages: tensorflow-estimator, tensorboard, tensorflow
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.2.1
    Uninstalling tensorboard-2.2.1:
      Successfully uninstalled tensorboard-2.2.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.2.0
    Uninstalling tensorflow-2.2.0:
      Successfully uninstalled tensorflow-2.2.0
Successfully installed tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-estimator-1.14.0
(base) jonasbjerg@jsb python_server % ./install.sh    
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0
ERROR: No matching distribution found for tensorflow==1.14.0
Requirement already satisfied: cython in /usr/local/lib/python3.8/site-packages (0.29.21)
Collecting pycocotools==2.0
  Using cached pycocotools-2.0.0.tar.gz (1.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-install-xt6yrq8n/pycocotools_55fd26e6dfbc48e88d682cbbc4de656c/setup.py'"'"'; __file__='"'"'/private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-install-xt6yrq8n/pycocotools_55fd26e6dfbc48e88d682cbbc4de656c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-pip-egg-info-erv6sjit
         cwd: /private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-install-xt6yrq8n/pycocotools_55fd26e6dfbc48e88d682cbbc4de656c/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_r/q67g21v57yb2c54yktvcpvrr0000gn/T/pip-install-xt6yrq8n/pycocotools_55fd26e6dfbc48e88d682cbbc4de656c/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(base) jonasbjerg@jsb python_server %
